spring:
  profiles:
    active: ${APP_PROFILE:dev}
  banner:
    location: classpath:/banner.txt
  application:
    name: Spring Security Demo

server:
  port: ${SERVER_PORT:8080}

application:
  title: Spring Security Demo
  version: 1.0.0